# CrystaShell - Configuração de Atalhos do Yazi
# Sistema completo de navegação por abas

# Criar nova aba
[[mgr.prepend_keymap]]
on = "t"
run = "tab_create --current"
desc = "Criar nova aba no diretório atual"

[[mgr.prepend_keymap]]
on = [ "<C-n>" ]
run = "tab_create --current"
desc = "Criar nova aba (Ctrl+N)"

# Fechar aba atual
[[mgr.prepend_keymap]]
on = [ "<C-w>" ]
run = "tab_close 0"
desc = "Fechar aba atual"

[[mgr.prepend_keymap]]
on = [ "<C-q>" ]
run = "tab_close 0"
desc = "Fechar aba atual (Ctrl+Q)"

# Navegação entre abas - Tab/Ctrl+Shift+Tab
[[mgr.prepend_keymap]]
on = [ "<Tab>" ]
run = "tab_switch 1 --relative"
desc = "Próxima aba"

[[mgr.prepend_keymap]]
on = [ "<C-S-Tab>" ]
run = "tab_switch -1 --relative"
desc = "Aba anterior (Ctrl+Shift+Tab)"

# Navegação estilo browser
[[mgr.prepend_keymap]]
on = [ "<C-Tab>" ]
run = "tab_switch 1 --relative"
desc = "Próxima aba (Ctrl+Tab)"

# Setas direcionais
[[mgr.prepend_keymap]]
on = [ "<C-Right>" ]
run = "tab_switch 1 --relative"
desc = "Próxima aba (Ctrl+→)"

[[mgr.prepend_keymap]]
on = [ "<C-Left>" ]
run = "tab_switch -1 --relative"
desc = "Aba anterior (Ctrl+←)"

# Acesso direto às abas (Alt+número)
[[mgr.prepend_keymap]]
on = [ "<A-1>" ]
run = "tab_switch 0"
desc = "Ir para aba 1"

[[mgr.prepend_keymap]]
on = [ "<A-2>" ]
run = "tab_switch 1"
desc = "Ir para aba 2"

[[mgr.prepend_keymap]]
on = [ "<A-3>" ]
run = "tab_switch 2"
desc = "Ir para aba 3"

[[mgr.prepend_keymap]]
on = [ "<A-4>" ]
run = "tab_switch 3"
desc = "Ir para aba 4"

[[mgr.prepend_keymap]]
on = [ "<A-5>" ]
run = "tab_switch 4"
desc = "Ir para aba 5"

[[mgr.prepend_keymap]]
on = [ "<A-6>" ]
run = "tab_switch 5"
desc = "Ir para aba 6"

[[mgr.prepend_keymap]]
on = [ "<A-7>" ]
run = "tab_switch 6"
desc = "Ir para aba 7"

[[mgr.prepend_keymap]]
on = [ "<A-8>" ]
run = "tab_switch 7"
desc = "Ir para aba 8"

[[mgr.prepend_keymap]]
on = [ "<A-9>" ]
run = "tab_switch 8"
desc = "Ir para aba 9"

# Navegação estilo Vim
[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "tab_switch 1 --relative"
desc = "Próxima aba (estilo Vim)"

[[mgr.prepend_keymap]]
on = [ "g", "T" ]
run = "tab_switch -1 --relative"
desc = "Aba anterior (estilo Vim)"

[[mgr.prepend_keymap]]
on = [ "g", "1" ]
run = "tab_switch 0"
desc = "Ir para aba 1 (estilo Vim)"

[[mgr.prepend_keymap]]
on = [ "g", "2" ]
run = "tab_switch 1"
desc = "Ir para aba 2 (estilo Vim)"

[[mgr.prepend_keymap]]
on = [ "g", "3" ]
run = "tab_switch 2"
desc = "Ir para aba 3 (estilo Vim)"

[[mgr.prepend_keymap]]
on = [ "g", "4" ]
run = "tab_switch 3"
desc = "Ir para aba 4 (estilo Vim)"

[[mgr.prepend_keymap]]
on = [ "g", "5" ]
run = "tab_switch 4"
desc = "Ir para aba 5 (estilo Vim)"

# Reordenar abas
[[mgr.prepend_keymap]]
on = [ "<C-S-Right>" ]
run = "tab_swap 1"
desc = "Mover aba para direita"

[[mgr.prepend_keymap]]
on = [ "<C-S-Left>" ]
run = "tab_swap -1"
desc = "Mover aba para esquerda"
