# CrystaShell - Configuração Principal do Yazi
# Configuração completa com suporte a previews avançados

[mgr]
ratio = [1, 4, 3]  # Layout com preview maior
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
show_hidden = true
show_symlink = true
linemode = "size"
mouse_events = ["click", "scroll"]
scrolloff = 5

[preview]
# Configurações otimizadas para terminal Linux nativo
wrap = "no"
tab_size = 4
max_width = 600
max_height = 400
cache_dir = "~/.cache/yazi"

# Configurações para imagens reais no terminal
image_filter = "lanczos3"
image_quality = 90
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

# Otimizado para GNOME Terminal
image_delay = 50

# Preview para diferentes tipos de arquivo
[[preview.previewers]]
name = "folder"
run = "folder"
cond = "mime=inode/directory"

[[preview.previewers]]
name = "code"
run = "code"
cond = "mime=text/*"

[[preview.previewers]]
name = "json"
run = "json"
cond = "mime=application/json"

[[preview.previewers]]
name = "archive"
run = "archive"
cond = "mime=application/(zip|gzip|x-tar|x-bzip2|x-7z-compressed)"

# Imagens - usar script personalizado CrystaShell
[[preview.previewers]]
name = "image"
run = "/home/paulo/projetos/CrystaShell/scripts/yazi_preview.sh"
cond = "mime=image/*"

# PDFs
[[preview.previewers]]
name = "pdf"
run = "pdf"
cond = "mime=application/pdf"

# Vídeos
[[preview.previewers]]
name = "video"
run = "video"
cond = "mime=video/*"

# Áudio
[[preview.previewers]]
name = "audio"
run = "audio"
cond = "mime=audio/*"

# Office documents
[[preview.previewers]]
name = "office"
run = "office"
cond = "mime=application/(msword|vnd.openxmlformats-officedocument|vnd.oasis.opendocument)"

[opener]
# Editores de texto
edit = [
    { run = 'code "$@"', block = false, for = "linux" },
    { run = 'vim "$@"', block = true },
]

# Visualizadores de imagem
image = [
    { run = 'feh "$@"', block = false, for = "linux" },
    { run = 'eog "$@"', block = false, for = "linux" },
    { run = 'xdg-open "$@"', block = false, for = "linux" },
]

# Visualizadores de PDF
pdf = [
    { run = 'zathura "$@"', block = false, for = "linux" },
    { run = 'evince "$@"', block = false, for = "linux" },
    { run = 'okular "$@"', block = false, for = "linux" },
    { run = 'xdg-open "$@"', block = false, for = "linux" },
]

# Players de vídeo
video = [
    { run = 'mpv "$@"', block = false, for = "linux" },
    { run = 'vlc "$@"', block = false, for = "linux" },
    { run = 'xdg-open "$@"', block = false, for = "linux" },
]

# Players de áudio
audio = [
    { run = 'mpv "$@"', block = false, for = "linux" },
    { run = 'audacious "$@"', block = false, for = "linux" },
    { run = 'xdg-open "$@"', block = false, for = "linux" },
]

# Navegadores web
web = [
    { run = 'firefox "$@"', block = false, for = "linux" },
    { run = 'chromium "$@"', block = false, for = "linux" },
    { run = 'xdg-open "$@"', block = false, for = "linux" },
]

# Arquivos compactados
archive = [
    { run = 'file-roller "$@"', block = false, for = "linux" },
    { run = 'ark "$@"', block = false, for = "linux" },
]

[open]
# Regras de abertura por tipo MIME
rules = [
    # Imagens
    { mime = "image/*", use = "image" },
    
    # PDFs
    { mime = "application/pdf", use = "pdf" },
    
    # Vídeos
    { mime = "video/*", use = "video" },
    
    # Áudio
    { mime = "audio/*", use = "audio" },
    
    # Texto e código
    { mime = "text/*", use = "edit" },
    { mime = "application/json", use = "edit" },
    { mime = "application/javascript", use = "edit" },
    { mime = "application/x-shellscript", use = "edit" },
    
    # Web
    { mime = "text/html", use = "web" },
    
    # Arquivos compactados
    { mime = "application/zip", use = "archive" },
    { mime = "application/gzip", use = "archive" },
    { mime = "application/x-tar", use = "archive" },
    { mime = "application/x-bzip2", use = "archive" },
    { mime = "application/x-7z-compressed", use = "archive" },
    
    # Office
    { mime = "application/msword", use = "pdf" },
    { mime = "application/vnd.openxmlformats-officedocument.*", use = "pdf" },
    { mime = "application/vnd.oasis.opendocument.*", use = "pdf" },
    
    # Fallback
    { mime = "*", use = "edit" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
